'use client';

import { createProduct } from "@/lib/actions";

export default function CreateProductForm({} : {}) {
    /**
        product_id: string;         // Autogenerated, omit
        user_id: string;            // Passed in (requires auth)
        product_name: string;       // User Value
        price_in_cents: number;     // User Value (convert to cents)
        category: string;           // User Value
        description: string;        // User Value
        image_url: string;          // User Value (requires Image thing I haven't built)
        created_at: Date;           // Generated on item creation, omit
     */
    // test user id until authentication lets us grab user id
    const user_id = '891ccb08-e0b6-4aba-a439-33154b58dff0';
    const createProductWithId = createProduct.bind(null, user_id);

    return (
        <form action={createProductWithId}></form>
    );
}